modLoader = "javafml"
loaderVersion = "[2,)" # Requires JavaFML 2.0 or newer
license = "MIT"

[[mods]]
modId = "cobblemoncreatified"
version = "1.0.0"
displayName = "Cobblemon Creatified"
authors = "Foresage"
description = '''
Enhances Cobblemon with custom spawns, repel mechanics, and shiny token mechanics.
Fully compatible with Create and dedicated servers.
'''
displayTest = "IGNORE_ALL_VERSION" # ✅ Ensures it's safe to load on dedicated servers

# Optional mixins configuration (only if you're using mixins)
[[mixins]]
config = "cobblemon/creatified/mixins.json"

# Required dependencies
[[dependencies.cobblemoncreatified]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.133,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemoncreatified]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemoncreatified]]
modId = "create"
type = "required"
versionRange = "[0.6.0.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemoncreatified]]
modId = "cobblemon"
type = "required"
versionRange = "[1.6.1,)"
ordering = "NONE"
side = "BOTH"

# Optional compatibility with spawn notification mod
[[dependencies.cobblemoncreatified]]
modId = "spawn_notification"
type = "optional"
versionRange = "*"
ordering = "NONE"
side = "BOTH"


[[dependencies.cobblemoncreatified]]
modId = "jei"
mandatory = false
versionRange = "[15.19.0,)"
ordering = "NONE"
side = "CLIENT"
